### ISSUE TITLE
Admin Portal

### ISSUE THREAD

**Issue by csteamengine** [ISU-WebDevClub/club-website#104]
Things to add in the admin portal redesign
# Main Tabs
- Members
- Projects
- Club Info (Meeting Dates/Times/Location, Policies, etc...)

These can be tabs at the top of the page, to add/edit members, click that tab etc... Shouldn't be very hard to do.
# Forms
- Members
  - Name
  - About
  - Officer?
  - Picture
  - Personal Website
- Projects
  - Title
  - Description
  - Image
  - External URL?
  - Dates
- Club Info
  - Meeting Dates/Times/Location
  - Club Description 
  - Other?
# Things To Consider
- Log in should probably be administered by shibboleth
- Database cannot have any confidential information
- Portal needs to be SSL protected (Levi will help with this)
# Specifics

Each Project and Member will need to be 'delete-able'/'hide-able' and if time allows, a cool option would be to drag to reorder members on the page. (or random placement again like we are already doing)

Members that are also officers could be placed on a separate officers page as well as the members page.

Member URL's for their websites will automatically open a new tab when clicked, but if the URL is blank we don't want any click action. It is annoying when the link just reloads the page (Ex// '#'). Same for projects unless we want to have a highlight page that dynamically loads the project you select. That wouldn't be too hard.

Meeting times could be a weekly/hourly selection box. 

Location COULD find a way to load Iowa State building into a drop down box (AJAX) with the rooms too, but it would be easier to just do a text box. After all, no one but the officers would be seeing this page. 
# Installing Shibboleth
- [Instructions](https://asw.iastate.edu/cgi-bin/acropolis/help?topic=admin%2Fshibboleth%2Fsp%2Fprimer)
- We don't want to require log in to the whole website, just the admin page.

**Comment by frostbyte100** [comment]
Marking this as closed since we are not allowed to complete this due to university restrictions.
