### ISSUE TITLE
0005 - Create Portfolio Page

### ISSUE THREAD

**Issue by KrashLeviathan** [ISU-WebDevClub/club-website#15]
Create a page that will act as a portfolio of all projects that we've completed as a club. Perhaps with a carousel, grid, or another interesting way of presentation. The page should be called "portfolio.html" and should be within a folder named "portfolio" (per the nav bar link).

**Comment by CivBase** [comment]
Starting

**Comment by CivBase** [comment]
https://github.com/ISU-WebDevClub/club-website/pull/28
