### ISSUE TITLE
0006 - Create a Contact page

### ISSUE THREAD

**Issue by KrashLeviathan** [ISU-WebDevClub/club-website#16]
Create a "contact.html" page within a "contact" folder (per the nav bar link). The contact page should have a form with entry fields that submit and send an email to isuwebdevclub@gmail.com. It should include relevant information about web development services we provide, joining the club, etc. The form should include input validation and other security measures ( @regalcat can help in this department ).

**Comment by regalcat** [comment]
Started progress
