### ISSUE TITLE
0007 - Create a Resources page

### ISSUE THREAD

**Issue by KrashLeviathan** [ISU-WebDevClub/club-website#17]
Create a "resources.html" page within a "resources" folder (per the nav bar link) that contains... well... resources. This page will have our dev blog, plus links to vetted dev tutorials, videos, etc. The dev blog is something that will probably be added later after launch, since it will involve setting up a back-end and content management system of some sort. We should definitely have civbase's (Branden's) git tutorial linked into here, since it's great material that was written by one of our own.

**Comment by RobertKloster** [comment]
Begun.

**Comment by KrashLeviathan** [comment]
PR [#29](https://github.com/ISU-WebDevClub/club-website/pull/29)

**Comment by KrashLeviathan** [comment]
Merged
