### ISSUE TITLE
0010 - Add Officers to Members page

### ISSUE THREAD

**Issue by KrashLeviathan** [ISU-WebDevClub/club-website#20]
Add officers to About Us page, with links to the officers' email addressed (you can find them in the Web Dev Club's [student organization page](https://www.stuorg.iastate.edu/site/web-dev-club/officers)).

**Comment by KrashLeviathan** [comment]
Starting work on this one

**Comment by csteamengine** [comment]
Working on this

**Comment by csteamengine** [comment]
NVM this code is beyond me

**Comment by csteamengine** [comment]
Claimed!

**Comment by frostbyte100** [comment]
This doesn't seem to be done? Is it?

**Comment by csteamengine** [comment]
Yeah I created a pull request last semester but I am not sure how up to date that PR is.

**Comment by frostbyte100** [comment]
Did you get Christine's summary? It seems like the pr isn't updated yet

**Comment by KrashLeviathan** [comment]
[Migrated to wdc-website repo](https://github.com/ISU-WebDevClub/wdc-website/issues/1)
