### ISSUE TITLE
0011 - Other club account info

### ISSUE THREAD

**Issue by KrashLeviathan** [ISU-WebDevClub/club-website#21]
Find a place to link to the club's GitHub account, Google Drive, Slack, and student organization page. Maybe on the Resources page? (For these links, [click here](https://www.stuorg.iastate.edu/site/web-dev-club/essential-information))

**Comment by RobertKloster** [comment]
The Resources page currently contains links to all above mentioned locations.

**Comment by KrashLeviathan** [comment]
Covered in [ticket 0007](https://github.com/ISU-WebDevClub/club-website/issues/17)
