### ISSUE TITLE
Add search bar to members page

### ISSUE THREAD

**Issue by KrashLeviathan** [ISU-WebDevClub/club-website#49]
As we add members, that page is going to fill up, and it will be difficult to find a specific person. Especially since the algorithm orders the grid in a random fashion every time (so no one always gets prime real estate at the top). As the person uses the search bar, it should filter out non-matches intelligently as they type.

**Comment by Skyman12** [comment]
Working on this.

**Comment by KrashLeviathan** [comment]
@Skyman12 were you able to make headway on this? If so, you should push it up to the [new repo](https://github.com/ISU-WebDevClub/wdc-website/)

**Comment by KrashLeviathan** [comment]
[Migrated to wdc-website repo](https://github.com/ISU-WebDevClub/wdc-website/issues/7)
