### ISSUE TITLE
Add real members to members page

### ISSUE THREAD

**Issue by KrashLeviathan** [ISU-WebDevClub/club-website#51]
This is probably a good one for each club member to do for their own member block, with help if needed. It will be a simple change you can make to see how the process works. You'll need to do the following:

1. Find a good quality picture (professional or silly, up to you) for your member image. Try to have it bigger than 512x512 but smaller than 1024x1024 pixels. We can use this nice pic later for other stuff.
2. Save it as `Lastname-Firstname-lg.jpg`
3. Make a copy, and crop / rescale it to 256x256. Save it as `Lastname-Firstname-md.jpg`
4. Make another copy, and crop / rescale it to 64x64. Save it as `Lastname-Firstname-sm.jpg` (We can use this resource later, say, for dev blog posts or such).
5. Now you should have three images: large, medium, and small. Save those to `/_images/members/` (if the folder isn't there yet, make it).
6. Update the `/members/members.json` file with your name, image path to the medium-sized picture, and a one-line description of yourself.
7. Push your changes to your fork, create a pull request, and you're good to go!

Once we get a handful of members who have uploaded pictures, we can take down the Nicolas Cage placeholders.

Keep this issue open until everyone is added! Obviously we'll add/remove people as the club grows/shrinks over time, but lets push to get everyone on at the start who's currently in the club.

**Comment by JackRometty** [comment]
do we have a list of members?

**Comment by KrashLeviathan** [comment]
We do, in the Student Organization Database. However, I think it would be good for people to add themselves so they can get a hang of the contributing process.

**Comment by KrashLeviathan** [comment]
Done
