### ISSUE TITLE
Add a "Getting Started" page for new members

### ISSUE THREAD

**Issue by CivBase** [ISU-WebDevClub/club-website#68]
### Story:

As a new member to the web dev club, I would want some documentation to guide me so that I can become familiar with how the club works and how I can join and participate in it.

### Acceptance Criteria:

- A "getting started" page exists and can be easily navigated to on the club website
- The page introduces GitHub and standard contribution practices
- The page introduces the WebStorm IDE
- The page provides simple, thorough instructions for adding a new member to the members page
- The page explains how to get involved with a web dev club project

### Dependencies:

- [x] None

**Comment by KrashLeviathan** [comment]
[Migrated to wdc-website repo](https://github.com/ISU-WebDevClub/wdc-website/issues/5)
