### ISSUE TITLE
Home Page has black bar all the way down the right side

### ISSUE THREAD

**Issue by csteamengine** [ISU-WebDevClub/club-website#79]
If you scroll side to side just a little bit, you will see that the home page has a black bar going all the way down the right side of the screen. Only occurs on the home page and only on the right side. You can see this in the pictures I added below, in case it is just on my computer. I have noticed that it happens on chrome and safari on my mac. 
The top Image shows the page before trying to side scroll.
<img width="1280" alt="screen shot 2015-11-18 at 10 42 12 am" src="https://cloud.githubusercontent.com/assets/11777512/11247292/0c3b1ea8-8de1-11e5-8dfb-66729de63c6a.png">

This image shows what happens when you side scroll.
<img width="598" alt="screen shot 2015-11-18 at 10 41 57 am" src="https://cloud.githubusercontent.com/assets/11777512/11247293/0c4290b6-8de1-11e5-9446-2f4f8b0f4342.png">

I believe it is related to the chalkboard cover image because it also occurs on the contact us page.

**Comment by shaun3141** [comment]
I think it's because there is an element that expands past 100% of the width, this can usually be caused by margins or divs with different kinds of the display property. 

I have a feeling that the chalkboard image is set to be 100% of the width which will work great once you find the content that sticks past 100% of it and remove it.

**Comment by csteamengine** [comment]
Fixed it, will create pull request, the problem was the jumbotron. For some reason when you would go from mobile back to desktop it thought it was wider than 100%. At least on safari. I just made it 90% width and it didn't change the way the title looked at all.

**Comment by KrashLeviathan** [comment]
@csteamengine this got fixed right?

**Comment by frostbyte100** [comment]
This is definitely completed now.
