### ISSUE TITLE
Timeline looks funky on mobile

### ISSUE THREAD

**Issue by KrashLeviathan** [ISU-WebDevClub/club-website#82]
The last item that's in the timeline on the About page looks funky when it's displayed on mobile (narrow screen). The bootstrap grid for that item (and maybe for the others too) needs to be adjusted so the pictures bump down or disappear or something.

![abouttimeline](https://cloud.githubusercontent.com/assets/8837587/11547911/38a23d7c-991d-11e5-8a44-e253e57b338c.jpg)

**Comment by csteamengine** [comment]
I'll see what I can do.

**Comment by KrashLeviathan** [comment]
Thanks! And thanks for tackling most of the other issues too.

**Comment by KrashLeviathan** [comment]
[Migrated to wdc-website repo](https://github.com/ISU-WebDevClub/wdc-website/issues/3)
