### ISSUE TITLE
Update Meeting time and Location

### ISSUE THREAD

**Issue by csteamengine** [ISU-WebDevClub/club-website#89]
The meeting time on the home page needs to be updated to reflect Spring 2016's meeting times. Will need to wait until the location has been confirmed, but should be confirmed within the next two days.

**Comment by frostbyte100** [comment]
Got it

**Comment by KrashLeviathan** [comment]
[Migrated to wdc-website repo](https://github.com/ISU-WebDevClub/wdc-website/issues/2)
